EQUIPO = "AGLS"
PORCENTAJES = [80, 65, 40, 80, 35, 55, 55, 60, 65, 30, 85, 45, 50, 55, 45, 45, 35, 45, 85, 55]
ITEMS = [
    ("1", r"Repositorio transferido, URL can\'onica en README, \rt{CITATION.cff}, macros y portada; portada y roles actualizados", 1, 1, 2, 1, "PM"),
    ("2a", r"Sin configuraci\'on de IDE, binarios pesados, bases SQLite hu\'erfanas ni \emph{journals} versionados", 1, 2, 3, 2, "PM"),
    ("2b", r"Credencial de PayPal del historial revocada y documentada y detector de secretos en CI", 2, 1, 1, 1, "PI"),
    ("2c", r"README sin afirmaciones falsas, mapa del Listado 3 y \rt{.gitattributes} general", 2, 1, 2, 2, "PM"),
    ("3", r"Trabajo por PR aprobados por otro integrante, \rt{CHANGELOG.md} y etiqueta anotada de cierre", 1, 1, 2, 2, "PC"),
    ("4", r"Capa de aplicaci\'on sin SQL, transacciones de framework ni excepciones HTTP; presentaci\'on sin infraestructura; ArchUnit", 3, 3, 3, 3, "PM"),
    ("5a", r"Strategy de pagos, Observer de pedidos, Decorator de promociones y Factory Method en el flujo real de checkout, con pruebas", 3, 3, 3, 4, "PI"),
    ("5b", r"ADR-006 de elecci\'on m\'ovil con alternativas nombradas y dos criterios medidos", 2, 1, 1, 1, "PC"),
    ("6", r"SPA: \rt{/main}, \rt{/settings}, \rt{/about}, guardas JWT, i18n es/en, token en memoria, checkout funcional, panel de vendedor, m\'etricas de administrador y cabecera de identidad segura", 3, 3, 4, 4, "PC"),
    ("7", r"Cobertura web $\ge$70\,\% sobre todo \rt{src/} con umbrales que fallen, artefacto \rt{dist} por commit y contenedor no root", 2, 3, 3, 3, "PC"),
    ("8", r"Notificaciones push por cambio real de estado del pedido, esc\'aner resuelto contra el backend y actualizaci\'on por arrastre", 3, 4, 3, 4, "PC"),
    ("9", r"Pruebas de los ViewModels, E2E instrumentada, APK del repositorio igual al del CI y \rt{versionCode} incremental", 3, 3, 3, 3, "PM"),
    ("10", r"Contratos sobre los clientes reales (web y Kotlin) verificados por los proveedores con estados, en un job que pueda fallar", 3, 3, 3, 3, "PC"),
    ("11", r"Migraciones completas aplicadas por herramienta y prueba de ca\'ida con escrituras concurrentes repetida", 2, 2, 2, 2, "PM"),
    ("12a", r"Cobertura backend $\ge$70\,\% por servicio sin filtros de alcance, con compuerta, incluido el gateway", 3, 3, 5, 5, "PC"),
    ("12b", r"Testcontainers en tres servicios, E2E de compra contra el stack real y Locust nominal y rampa con checkout", 2, 3, 3, 3, "PC"),
    ("13", r"DAG \'unico que condiciona la publicaci\'on a todas las pruebas e integraci\'on con compose y sonda de salud", 3, 3, 2, 3, "PC"),
    ("14", r"M\'etricas con los nombres exigidos, scrape de CockroachDB y contenedores, Collector, seis paneles y registros del m\'ovil", 3, 3, 4, 3, "PM"),
    ("15a", r"Protocolo con hip\'otesis, umbrales, potencia, $r=10$ y orden aleatorizado versionado antes de medir", 4, 2, 2, 2, "PC"),
    ("15b", r"Campa\~na 2PC/Saga sin saturaci\'on, con or\'aculo prospectivo, una sola poblaci\'on y recursos medidos", 4, 4, 4, 5, "PC"),
    ("16", r"Paquete can\'onico \'unico, diccionario de datos, manifiesto de todos los datos y volcado que haga regenerable el or\'aculo", 3, 3, 4, 3, "PC"),
    ("17", r"ISO/IEC 25010 con las cinco caracter\'isticas de la Tabla 2 (incluida compatibilidad) y r\'eplicas reales", 3, 3, 3, 4, "PC"),
    ("18", r"Manuscrito con la estructura de la Tabla 3, tablas generadas desde CSV can\'onicos, portada, compilaci\'on limpia documentada y hash vigente", 3, 2, 4, 4, "PC"),
    ("19", r"Amenazas actualizadas a la nueva campa\~na con mitigaci\'on expl\'icita y ACM Code of Ethics 2018 aplicado", 2, 1, 1, 1, "PM"),
    ("20", r"Actas por sesi\'on coherentes con el historial, PR aprobados por otro integrante y autor\'ia por \'item", 1, 1, 2, 2, "PM"),
]
