EQUIPO = "FUVV"
PORCENTAJES = [75, 70, 25, 65, 70, 75, 80, 70, 60, 60, 75, 70, 70, 60, 60, 60, 55, 55, 80, 55]
ITEMS = [
    ("1", r"URL can\'onica, nombre \'unico del sistema y del equipo, autores completos en \rt{CITATION.cff}", 1, 1, 2, 1, "PM"),
    ("2", r"\rt{LICENSE}, \rt{.env.example} con web y m\'ovil, retirar el PDF de calificaci\'on, mapa del Listado 3 y \rt{.gitattributes} de datos", 1, 2, 2, 1, "PM"),
    ("3", r"Integraci\'on a \rt{main} por PR con revisi\'on sustantiva y CI en verde, etiqueta anotada de cierre y \rt{CHANGELOG.md}", 2, 2, 3, 2, "PC"),
    ("4a", r"Cero dependencias de \rt{application} hacia \rt{infrastructure} y \rt{presentation} (228 imports en 56 archivos)", 3, 3, 4, 4, "PM"),
    ("4b", r"Dominio sin tipos Spring/JPA, paquetes heredados de reservas reubicados y reglas ArchUnit en \rt{mvn verify}", 2, 2, 3, 3, "PM"),
    ("5a", r"Observer de alertas con dos o m\'as suscriptores reales y Strategy con dos o m\'as pol\'iticas de reserva seleccionables", 3, 3, 3, 3, "PC"),
    ("5b", r"Singleton del cliente Prometheus conforme, expiraci\'on por el patr\'on State y ADR-005/006 exactos", 2, 2, 2, 2, "PM"),
    ("6", r"Internacionalizaci\'on de toda la SPA, \rt{/settings} y \rt{/about} para todo usuario, inicio real y tema oscuro coherente", 1, 2, 4, 3, "PM"),
    ("7", r"Cobertura web $\ge$70\,\% sobre todo \rt{src/} y E2E Playwright sin saltos, ejecutadas en verde", 2, 3, 3, 3, "PM"),
    ("8a", r"APK release contra el gateway real (sin \rt{10.0.2.2} ni HTTP plano) y QR que abre la reserva r\'apida", 2, 2, 2, 2, "PM"),
    ("8b", r"Notificaciones push FCM de extremo a extremo al crear incidentes, con evidencia de recepci\'on", 3, 4, 3, 3, "PC"),
    ("9a", r"Pruebas m\'oviles JUnit 5, cobertura $\ge$70\,\% con compuerta y E2E instrumentada login$\rightarrow$lista$\rightarrow$detalle", 3, 3, 4, 4, "PC"),
    ("9b", r"APK firmado generado desde \rt{main} tras las pruebas y publicado de forma verificable", 2, 2, 1, 1, "PM"),
    ("10a", r"Contratos generados por los clientes reales (web y m\'ovil) y verificados contra el proveedor arrancado, incluido auth", 3, 3, 3, 4, "PM"),
    ("10b", r"Validaci\'on de esquemas OpenAPI no circular como compuerta de publicaci\'on", 2, 3, 2, 2, "PM"),
    ("11", r"Experimento de ca\'ida de nodos reproducible, verificador de CI corregido y l\'imite de licencia resuelto o justificado", 3, 3, 2, 3, "PM"),
    ("12", r"Informes de las cinco capas de pruebas como artefactos y carga nominal y rampa repetidas con el harness corregido", 2, 3, 3, 3, "PM"),
    ("13", r"Pipeline completo en verde en el commit final, lint en los cinco servicios y compuertas completas antes de publicar", 2, 3, 3, 2, "PM"),
    ("14a", r"Seis paneles con datos bajo carga, cuatro m\'etricas nuevas en los servicios y traza distribuida exportada", 2, 3, 3, 3, "PM"),
    ("14b", r"Latencia extremo a extremo medida en el cliente m\'ovil y propagada con \rt{traceparent}", 3, 4, 3, 3, "PI"),
    ("15a", r"Campa\~na correctiva de fiabilidad 10\,$\times$\,1\,h ejecutada y versionada, sin 401 inducidos por el instrumento", 3, 3, 2, 4, "PC"),
    ("15b", r"ARBITER: $n$ suficiente en Esc-1, escenarios que ejerciten I4 e I5 y censo HTTP de todos los escenarios", 4, 3, 3, 3, "PM"),
    ("16", r"Manifiestos que verifican en cualquier clon y en CI, CSV can\'onico \'unico y datos de toda ejecuci\'on citada", 2, 2, 3, 3, "PM"),
    ("17", r"ISO/IEC 25010 sobre la poblaci\'on v\'alida: fiabilidad corregida, complejidad ciclom\'atica, seguridad por endpoint y compatibilidad API 26/34", 3, 3, 3, 3, "PM"),
    ("18", r"Manuscrito: estructura de la Tabla 3, res\'umenes $\ge$200 palabras, capturas exigidas, PDF versionado, instant\'anea E4 congelada y cifras can\'onicas", 2, 2, 3, 3, "PM"),
    ("19", r"Amenazas de sesi\'on y licencia con mitigaci\'on real y reflexi\'on \'etica $\ge$\textonehalf{} p\'agina", 2, 1, 1, 1, "PM"),
    ("20", r"Actas contempor\'aneas, PR revisados por otro integrante y declaraci\'on de uso de IA con alcance", 1, 1, 2, 2, "PM"),
]
