services:
  postgres:
    image: postgres:16-alpine@sha256:e013e867e712fec275706a6c51c966f0bb0c93cfa8f51000f85a15f9865a28cb
    container_name: storeproc-postgres
    environment:
      POSTGRES_DB: facturacion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Guayaquil
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d facturacion"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: